- repo: https://github.com/digitalpulp/pre-commit-php.git
  sha: 1.3.0
  hooks:
  - id: php-lint
  - id: php-unit
  - id: php-cbf
    files: \.(php)$
    args: [--standard=PSR2 --ignore=**/*.blade.php -p]
  - id: php-cs-fixer
    files: \.(php)$
    args: [--rules=@PSR2]

-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.2
    hooks:
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: end-of-file-fixer
